/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { IoTSpacesClientContext } from "./ioTSpacesClientContext";
import { IoTSpacesClientOptionalParams } from "./models";

export class IoTSpacesClient extends IoTSpacesClientContext {
  /**
   * Initializes a new instance of the IoTSpacesClient class.
   * @param options The parameter options
   */
  constructor(options?: IoTSpacesClientOptionalParams) {
    super(options);
  }
}
