name: check-code-format-push
run-name: Checking the Code format of the push ${{ github.sha }}
on: [push]
jobs:
  check-code-format:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Code
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Rush
        run: npm install -g @microsoft/rush
      - name: Update rush
        run: rush update
